"""
export_yolo_onnx.py
===================
Exports a trained YOLOv8 detection model to ONNX and then applies
dynamic INT8 quantisation for faster CPU / edge inference.

Two-step process
----------------
Step 1 — ONNX export via Ultralytics (uncomment the block below on first run)
Step 2 — Dynamic INT8 quantisation via ONNX Runtime

Outputs
-------
    best.onnx       — generated by Ultralytics export (Step 1)
    best_int8.onnx  — INT8 quantised model (Step 2)

Requirements
------------
    pip install ultralytics onnxruntime

Usage
-----
    # 1. Run Step 1 once to produce best.onnx, then comment it out.
    # 2. Run Step 2 (always) to quantise.
    python export_yolo_onnx.py
"""

from ultralytics import YOLO
from onnxruntime.quantization import quantize_dynamic, QuantType

# ---------------------------------------------------------------------------
# Checkpoint path — update to match your Stage 2 output directory
# ---------------------------------------------------------------------------
WEIGHTS_PT   = "runs/detect/runs/european_art/stage2_full-6/weights/best.pt"
WEIGHTS_ONNX = "runs/detect/runs/european_art/stage2_full-6/weights/best.onnx"
INT8_PATH    = "best_int8.onnx"

# ---------------------------------------------------------------------------
# Step 1 — Export to ONNX
# ---------------------------------------------------------------------------
# Uncomment the three lines below on the FIRST run.
# They produce best.onnx next to best.pt.
# After that, comment them out so you only re-quantise without re-exporting.

# model = YOLO(WEIGHTS_PT)
# model.export(format="onnx", imgsz=640, dynamic=True, simplify=True)
# # produces: <weights dir>/best.onnx

# ---------------------------------------------------------------------------
# Step 2 — Dynamic INT8 quantisation
# ---------------------------------------------------------------------------
# Replaces FP32 weight tensors with INT8.
# No calibration dataset needed (weights-only quantisation).
# Typical result: ~4× smaller file, slight accuracy trade-off.
quantize_dynamic(
    model_input=WEIGHTS_ONNX,
    model_output=INT8_PATH,
    weight_type=QuantType.QInt8,
)
print(f"Generated: {INT8_PATH}")
