"""
train_yolo.py
=============
Two-stage YOLOv8 fine-tuning on the European Art (DEArt) dataset.

Strategy
--------
Stage 1 — head-only warm-up (20 epochs)
    Backbone weights are frozen so only the detection head learns.
    This avoids destroying ImageNet/COCO pre-trained features at the
    start of training, when the randomly-initialised head would
    otherwise produce large, noisy gradients.

Stage 2 — full fine-tuning (50 epochs)
    All layers are unfrozen and trained with a lower LR + cosine
    schedule so the backbone adapts gently to the art domain.

Requirements
------------
    pip install ultralytics

Dataset
-------
    Run data_process.ipynb first to generate dataset_yolo/
    The expected layout is:
        dataset_yolo/
            dataset.yaml
            images/train/   images/val/
            labels/train/   labels/val/
"""

from ultralytics import YOLO

# ---------------------------------------------------------------------------
# Stage 1 — head-only warm-up (backbone frozen)
# ---------------------------------------------------------------------------

# Load a pre-trained YOLOv8 nano model (COCO weights).
# Other size options: yolov8s.pt  yolov8m.pt  yolov8l.pt  yolov8x.pt
model = YOLO("yolov8n.pt")

model.train(
    data="dataset_yolo/dataset.yaml",   # Path to the YAML generated by data_process.ipynb
    epochs=20,
    imgsz=640,
    batch=32,
    workers=4,
    device=0,                           # GPU index; use device="cpu" if no GPU available
    amp=True,                           # Mixed precision (FP16) — saves ~40 % VRAM
    cache="ram",                        # Load entire dataset into RAM for faster I/O.
                                        # Switch to cache="disk" if RAM < 16 GB.
    freeze=21,                          # Freeze layers 0-21; only the Detect head (layer 22) trains
    lr0=1e-2,                           # Initial learning rate — relatively high for head-only phase
    project="runs/european_art",
    name="stage1_head",
)

# ---------------------------------------------------------------------------
# Stage 2 — full fine-tuning (all layers unfrozen)
# ---------------------------------------------------------------------------

# Load the best checkpoint saved by Stage 1
model = YOLO("runs/detect/runs/european_art/stage1_head/weights/best.pt")

model.train(
    data="dataset_yolo/dataset.yaml",
    epochs=50,
    patience=5,                         # Early-stop if val metric does not improve for 5 epochs
    imgsz=640,
    batch=32,
    workers=4,
    device=0,
    amp=True,                           # Mixed precision (FP16)
    cache="disk",                       # Disk cache is safer when RAM is limited
    freeze=0,                           # Unfreeze all layers
    lr0=1e-4,                           # Low LR — avoids overwriting COCO-pre-trained weights aggressively
    lrf=0.01,                           # Final LR = lr0 * lrf (cosine decay target)
    momentum=0.937,
    weight_decay=0.0005,
    optimizer="AdamW",
    warmup_epochs=3,                    # Linear LR warm-up to avoid large updates at epoch 0
    cos_lr=True,                        # Cosine annealing LR schedule
    project="runs/european_art",
    name="stage2_full",
)
